apiVersion: apps/v1
kind: Deployment
metadata:
  name: enhanced-devops
  labels:
    app: enhanced-devops
spec:
  replicas: 3
  selector:
    matchLabels:
      app: enhanced-devops
  template:
    metadata:
      labels:
        app: enhanced-devops
    spec:
      containers:
        - name: {{ .Values.devops.name }}
          image: {{ .Values.devops.image.name }}:{{ .Values.devops.image.tag }}
