apiVersion: apps/v1
kind: Deployment
metadata:
  name: new-devops-deployment
  labels:
    app: new-devops
spec:
  replicas: 3
  selector:
    matchLabels:
      app: new-devops
  template:
    metadata:
      labels:
        app: new-devops
    spec:
      containers:
        - name: enhanced-devops
          image: enhanced-devops:latest
          ports:
            - containerPort: 80
      imagePullSecrets:
        - name: acr-secret